name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/easbarba/onur-go:0.5.0

    steps:
      - name: integration tests
        run: go test -v ./...
